apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
spec:
  containers:
  - name: demo
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath:  /etc/config
  volumes:
  - name: config-volume
    configMap:
        name: app-config

# test: apply the file and run  kubectl exec -it <pod-name> -- cat /etc/config/<env-var>